---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: add ingress class
patch: |-
  - op: add
    path: /metadata/annotations/kubernetes.io~1ingress.class
    value: nginx
target:
  kind: Ingress
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas add ingress class
patch: |-
  - op: add
    path: /spec/ingressTemplate/metadata/annotations/kubernetes.io~1ingress.class
    value: nginx
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1
